# -*- coding: utf-8 -*-
"""Netflix_project_asit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16kpOit7sQ8dUhSGcxHtzfdbGQFQgO0YX
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive

netflix_dataset=pd.read_csv("/content/drive/MyDrive/Netflix/combined_data_1.txt.zip",header=None , names=["Cust_Id" , "Rating"] , usecols=[0,1])

netflix_dataset

netflix_dataset.info()

# check for null value/missing value
netflix_dataset.isnull().sum()
# for movie id there is no ratings

# UNDERSTAND THE DATA-
# how many movies ?
# how many customers?
# how many ratings there?

# Get the count of movies with the help of Cust_Id and Rating columns
movie_count = netflix_dataset.isnull().sum()['Rating']
# Number of NaN values in Rating = Number of movies
movie_count

# to calculate how many unique users/customers are there
total_count = netflix_dataset['Cust_Id'].nunique()
total_count

# but we know that in Cust_Id -> movie_id + customer_id
# So , let's find out the customer id
customer_count = total_count - movie_count
customer_count

# To calculate how many ratings do we have that are given by the users
rating_count = netflix_dataset['Cust_Id'].count() - movie_count
rating_count

# NOW LET'S UNDERSTAND THE RATING DISTRIBUTION
# To find out how many users have rated  the movie as  1 , 2 ,3 ,4 ,5 stars
stars = netflix_dataset.groupby('Rating')['Rating'].count()
stars

# This counts how many 1-star, 2- star , 3-star , 4-star , 5-star exists

ax = stars.plot(kind='barh',legend=False,figsize=(10,7),color='pink',edgecolor='red')
plt.title(f' Total Movie : {movie_count}, Total customer:{customer_count}, Total number of ratings:{rating_count}', fontsize=20)
plt.grid(True)
plt.show()

# CREATE A SEPARATE MOVIE ID COLUMN
# Because SVD can't work on messy real-world data/id's  - so we need clean , compact and proper data

movie_id = None # the movie which we are currently reading
movie_np = [] # list where we will save the movie id for each row

for i in netflix_dataset['Cust_Id']:
  if ":" in i:
    movie_id = int(i.replace(":",""))  # extract movie number

  movie_np.append(movie_id)

movie_np

# create a new column-
netflix_dataset["Movie_Id"] = movie_np

netflix_dataset

# CLEANING THE DATA -
netflix_dataset = netflix_dataset[netflix_dataset["Rating"].notna()]
netflix_dataset

netflix_dataset.info()

netflix_dataset['Cust_Id'] = netflix_dataset['Cust_Id'].astype(int)

netflix_dataset.info()

# PRE - FILTERTING:-
# Remove users and movies that provide little or unreliable information before training the model

"""**we will remove users with very few ratings -> because they confuse the model**

**movies with very few ratings- because it is statiscally meaningless**  
"""

#  count the rating of movie_id-
dataset_movie_summary = netflix_dataset.groupby("Movie_Id")["Rating"].agg(['count', 'mean', 'max'])

dataset_movie_summary

movie_benchmark = round(dataset_movie_summary['count'].quantile(0.6),0)
movie_benchmark

drop_movie_list = dataset_movie_summary[dataset_movie_summary['count'] < movie_benchmark].index
drop_movie_list

len(drop_movie_list)

dataset_cust_summary = netflix_dataset.groupby('Cust_Id')['Rating'].agg(['count'])
dataset_cust_summary

cust_benchmark = round(dataset_cust_summary['count'].quantile(0.6),0)
cust_benchmark

drop_cust_list = dataset_cust_summary[dataset_cust_summary['count'] < cust_benchmark].index
drop_cust_list

len(drop_cust_list)

# NOW WE WILL REMOVE THIS DATA FROM OUR DATASET
netflix_dataset = netflix_dataset[~netflix_dataset['Movie_Id'].isin(drop_movie_list)]
netflix_dataset = netflix_dataset[~netflix_dataset['Cust_Id'].isin(drop_cust_list)]

netflix_dataset

netflix_dataset

df_title = pd.read_csv("/content/drive/MyDrive/Netflix/movies (1) (1).csv",encoding='ISO-8859-1',usecols=[0,1,2])
df_title

df_title.rename(columns={'movieId':'Movie_Id'},inplace=True)

df_title

pip install numpy==1.26.4

import numpy as np
print(np.__version__)

!pip install scikit-surprise

from surprise import Reader, Dataset, SVD
from surprise.model_selection import cross_validate

reader = Reader()

data = Dataset.load_from_df(netflix_dataset[['Cust_Id','Movie_Id','Rating']][:100000],reader)

data

model = SVD()

cross_validate(model,data,measures=['RMSE'],cv=3)

# Cust_Id =1331154

user_rating = netflix_dataset[netflix_dataset["Cust_Id"]==1331154]
user_rating

user_1331154 = df_title.copy()
user_1331154

user_1331154 = user_1331154[~user_1331154['Movie_Id'].isin(drop_movie_list)]

user_1331154

user_1331154["Estimated_Score"] = user_1331154["Movie_Id"].apply(lambda x:model.predict(1331154,x).est)

user_1331154

user_1331154.sort_values('Estimated_Score',ascending=False,inplace=True)

user_1331154.head(5)